name: Add Icon
description: Suggest a service that support two-factor authentication (TOTP)
title: Add [service name]
labels: json
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Exact service name
      placeholder: ex. Dropbox
    validations:
      required: true
  - type: input
    id: domain
    attributes:
      label: Domain name
      description: 
      placeholder: ex. dropbox.com
    validations:
      required: true
  - type: input
    id: documentaion
    attributes:
      label: Documentation URL
      description: Link to documentation on how to enable 2FA on the site.
      placeholder: ex. https://help.dropbox.com/account-access/enable-two-step-verification
  - type: checkboxes
    id: 2fa
    attributes:
      label: Supported two-factor authentication method
      description: The service icon you request must support two-factor authentication, TOTP algoritm
      options:
        - label: TOTP (Google Authenticator)
          required: true
        - label: U2F
        - label: sms
        - label: email