name: Add Icon
description: Suggest a service that support two-factor authentication (TOTP)
title: Add TEST
labels: json
body:
  - type: input
    id: service_name
    attributes:
      label: Name
      description: Exact service name
      # placeholder: ex. Dropbox
      value: Dropbox
    validations:
      required: true
  - type: input
    id: domain_name
    attributes:
      label: Domain
      description: Exact domain name
      # placeholder: ex. dropbox.com
      value: dropbox.com
    validations:
      required: true
  - type: input
    id: documentaion_url
    attributes:
      label: Documentation
      description: Link to documentation on how to enable 2FA on the site.
      # placeholder: ex. https://help.dropbox.com/account-access/enable-two-step-verification
      value: https://help.dropbox.com/account-access/enable-two-step-verification
  - type: input
    id: recovery_url
    attributes:
      label: Recovery
      description: Link to documentation on how to recover access on the site.
      # placeholder: ex. https://help.dropbox.com/recovery/
      value: https://help.dropbox.com/recovery
  - type: checkboxes
    id: 2fa_method
    attributes:
      label: Supported 2FA Methods
      description: The service icon you request must support two-factor authentication, TOTP algoritm
      options:
        - label: totp
          required: true
        - label: u2f
        - label: sms
        - label: email