name: Add Icon
description: Suggest a service that support two-factor authentication (TOTP)
title: Add TEST
labels: json
body:
  - type: input
    id: service_name
    attributes:
      label: Name
      description: Exact service name
      # placeholder: ex. Dropbox
      value: Dropbox
    validations:
      required: true
  - type: input
    id: domain_name
    attributes:
      label: Domain
      description: 
      placeholder: ex. dropbox.com
    validations:
      required: true
  - type: input
    id: documentaion_url
    attributes:
      label: Documentation
      description: Link to documentation on how to enable 2FA on the site.
      placeholder: ex. https://help.dropbox.com/account-access/enable-two-step-verification
  - type: checkboxes
    id: 2fa_method
    attributes:
      label: Supported 2FA Methods
      description: The service icon you request must support two-factor authentication, TOTP algoritm
      options:
        - label: TOTP (Google Authenticator)
          required: true
        - label: U2F
        - label: sms
        - label: email