name: Built with Eleventy
description: Show off your Eleventy site on the Eleventy documentation
title: "[Built with Eleventy] I built something!"
labels: built-with-eleventy
body:
  - type: input
    id: name
    attributes:
      label: Site URL
      description: The home page of the live web site you built. _[parser:url]_
      value: Dropbox
    validations:
      required: true
  - type: input
    id: domain
    attributes:
      label: Site URL
      description: The home page of the live web site you built. _[parser:url]_
      value: dropbox.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please note that site HTML must now include a `<meta name="generator" content="Eleventy">` (or at least `Eleventy` somewhere in the `content` attribute) to be eligible for the Eleventy Leaderboards.
  - type: input
    id: documentation
    attributes:
      label: Source code URL
      description: "Optional: The URL to the **public** repository for the source code for this site. _[parser:url]_"
      value: https://help.dropbox.com/account-access/enable-two-step-verification
    validations:
      required: false
  - type: textarea
    id: tfa
    attributes:
      label: "Authors (GitHub usernames)"
      description: "Optional: _Leave this empty if you are the only author._ If you are listing one or more other authors, make sure to include yourself in this list! _[parser:usernames]_"
      value: "totp"
    validations:
      required: false
  - type: checkboxes
    id: tfa
    attributes:
      label: Supported 2FA Methods
      description: "The service icon you request must support two-factor authentication, TOTP algoritm _[parser:usernames]_"
      options:
        - label: sms
        - label: email