name: create a json file from "Add Icon" template when a new issue is opened with label "json"
on:
  issues:
    types:
      - labeled

jobs:
  create-json-from-issue:
    if: github.event.label.name == 'json'
    runs-on: ubuntu-latest
    env:
      BODY: ${{ toJson(github.event.issue.body) }}
      BRANCH_NAME: 'buffer'
      JSON_FILE_NAME: "${{ github.event.issue.title }}.json"
      DUPLICATE_LABEL: 'duplicate' # Specify the label for duplicates

    steps:
      - name: Check Out Scripts
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Fetch 'buffer' branch
        run: |
          git fetch origin $BRANCH_NAME

      - name: Check for duplicate JSON file
        run: |
          if git ls-remote --exit-code origin refs/heads/$BRANCH_NAME:$JSON_FILE_NAME; then
            echo "The JSON file already exists."
            echo "Adding the '$DUPLICATE_LABEL' label to the issue."
            gh issue add-label ${{ github.event.issue.number }} "$DUPLICATE_LABEL"
            exit 0
          else
            echo "The JSON file does not exist. Proceeding to create it."
            exit 1
          fi
      
      - name: Create JSON file
        run: |
          node script.js
        env:
          BODY: ${{ env.BODY }}

      - name: Commit and push JSON file
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout $BRANCH_NAME
          git add . -A
          git commit -m "Add JSON file from issue body"
          git push origin $BRANCH_NAME