name: create a json file from "Add Icon" template when a new issue is opened with label "json"
on:
  issues:
    types:
      - labeled

jobs:
  create-json-from-issue:
    if: github.event.label.name == 'json'
    runs-on: ubuntu-latest
    env:
      BODY: ${{ toJson(github.event.issue.body) }}
    steps:
      - name: Check out scripts
        uses: actions/checkout@v3

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          node script.js
        env:
          BODY: ${{ env.BODY }}

      - name: set domain name
        id: domain-name
        run: |
          myValue=$(cat myValue.txt)
          echo "MY_VALUE=$myValue" >> "$GITHUB_OUTPUT"
      - name: get domain name
        env:
          MY_VALUE: ${{ steps.domain-name.outputs.MY_VALUE }}
        run: echo "The domain name is $MY_VALUE"

      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

      # - name: Commit
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "github-actions"
      #     git pull
      #     git add . -A
      #     git commit --allow-empty -a -m "issue_id: #${{ github.event.issue.number }}"

      # - name: Push
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}

      # - name: Add Label
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.addLabels({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         labels: ['automated']
      #       })
      # - name: Add Comment
      #   uses: peter-evans/create-or-update-comment@v3
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: Path to the json file in -> https://github.com/TFAuthentication/twofactorauth/tree/master/entries/zauthenticator/
