name: create a json file from "Add Icon" template when a new issue is opened with label "json"
on:
  issues:
    types:
      - labeled

jobs:
  create-json-from-issue:
    if: github.event.label.name == 'json'
    runs-on: ubuntu-latest
    env:
      BODY: ${{ toJson(github.event.issue.body) }}
      NEW_BRANCH_NAME: 'buffer'
    steps:
      - name: Check out scripts
        uses: actions/checkout@v3

      - name: node
        uses: actions/setup-node@v3
      - run: |
          # Execute your JavaScript file here
          node script.js
        env:
          BODY: ${{ env.BODY }}

      - name: Commit and push JSON file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git checkout -b $NEW_BRANCH_NAME
          git add -A
          git commit -m "Add JSON file from issue body"
          git push origin $NEW_BRANCH_NAME