name: create a json file when a new issue is opened with label json
on:
  issues:
    types:
      - labeled

jobs:
  add-comment:
    if: github.event.label.name == 'json'
    runs-on: ubuntu-latest
    env:
      BODY: ${{ toJson(github.event.issue.body) }}
    env:
      TEST: test
    steps:
      - name: Check out scripts
        uses: actions/checkout@v3

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          node script.js
        env:
          BODY: ${{ env.BODY }}

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git pull
          git add . -A
          git commit --allow-empty -a -m "${{ env.TEST }}"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Add comment
        uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ toJson(github.event.issue.body) }}
