name: create a json file from "Add Icon" template when a new issue is opened with label "json"
on:
  issues:
    types:
      - labeled

jobs:
  create-json-from-issue:
    if: github.event.label.name == 'json'
    runs-on: ubuntu-latest
    env:
      BODY: ${{ toJson(github.event.issue.body) }}
      BRANCH_NAME: 'buffer'
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch 'buffer' branch
        run: |
          git fetch origin $BRANCH_NAME

      - name: Check out 'buffer' branch or create it if not exists
        run: |
          if git show-ref --quiet "refs/heads/${BRANCH_NAME}"; then
            git checkout $BRANCH_NAME
          else
            git checkout -b $BRANCH_NAME
          fi

      - name: Create JSON file
        run: |
          # Execute your JavaScript file here
          node script.js
        env:
          BODY: ${{ env.BODY }}

      - name: Commit and push JSON file
        run: |
          git add -A
          git commit -m "Add JSON file from issue body"
          git push origin $BRANCH_NAME