
name: create a json file when a new issue is opened
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'json'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
        with:
          issue-number: ${{ github.event.issue.number }}
          issue-name: ${{ github.event.issue.name }}
          body: |
            ${{ github.event.issue.name }}