
name: create a json file when a new issue is opened
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'json'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Parse Issue Body
        uses: peter-murray/issue-body-parser-action@v1
        id: issue_body_parser
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This is assuming that you are triggering off the issue, otherwise you will need to know the issue number
          issue_id: ${{ github.event.issue.number }}