
name: create a json file when a new issue is opened
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'json'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Issue Body Parser
        uses: peter-murray/issue-body-parser-action@v2.0.1
