
name: create a json file when a new issue is opened
on:
  issues:
    types:
      - labeled
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Json Generate
        run: pwd