
name: create a json file when a new issue is opened
on:
  issues:
    types:
      - opened
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    name: Convert New built-with-eleventy Issue to Sites Data
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Swift Generate
        run: pwd