
name: create a json file when a new issue is opened
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'json'
    runs-on: ubuntu-latest
    env:
      BODY: ${{ toJson(github.event.issue.body) }}
    steps:
      - name: Check out scripts
        uses: actions/checkout@v3

      - name: Add comment
        uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ toJson(github.event.issue.body) }}
      
      - name: run script
        run: |
          cd scripts && node json.js
