name: Parse Issue in JavaScript and Save Data

on:
  issues:
    types: [opened]

jobs:
  save-data:
    runs-on: ubuntu-latest
    env:
      BODY: ${{ toJson(github.event.issue.body) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Parse Issue and Save Data
      run: node script.js ${{ env.BODY }}
