name: Create Comment on GitHub Issue

on:
  push:
    branches:
      - master

jobs:
  create-comment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JavaScript script
        run: |
          npm install axios
          node script.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY}}
