name: My GitHub Actions Workflow

on:
  push:
    branches:
      - master

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run JavaScript script
        run: |
          node script.js

      - name: Use the captured value
        run: |
          echo "The captured value is: ${{ steps.my-job.outputs.NewName }}"
